---
title: "hydrograph visualization"
author: "Youchen"
date: "4/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source('function_0_loadLibrary.R')
# install.packages("cowplot")
```

This document visualizes time series data of temperature, precipitation, relative residuals (defined below), and discharge, which include observations (**obs**), pcrglobwb predictions(**pcr**), predictions corrected by multiple linear regression(**pcr_glm**), and predictions corrected by random forests(**pcr_rf**).

rel_res(%) = (obs-pcr)/obs*100 

## Train period

```{r}
calibrMod <- 'calibrated'      # calibrated    uncalibrated
station_i <- 2                         # station id
stationInfo <- read.csv('../data/rawData/stationLatLon.csv')
station <- stationInfo$station %>% tolower

plotTitle <- station[station_i]

rf.result <- read.csv(paste0('../data/analysis/result_', calibrMod,'/rf_result_', station[station_i], '.csv'), header = T) %>% 
    mutate(datetime=as.Date(datetime))

plotHydrograph <- function(i){
    p <- ts_q2 %>% 
        filter(grepl(as.character(i),datetime))
    
    p <- gather(p, key='model', value='value', c('obs','pcr','pcr_corrected'))
    
    g0 <- ggplot(p, aes(datetime, t, col=temp0))+
        geom_line(aes(group = 1))+
        scale_color_manual(values=c('blue','red'))+
        scale_x_date(date_labels = '%b', date_breaks = '1 month')+
        ylab("Temp (*C)") +
        theme_bw(base_size = 12)+
        theme(legend.position = "none",
              axis.title.x    = element_blank(),
              axis.text.x     = element_blank(),
              axis.ticks.x    = element_blank())+
        theme(panel.grid.major.x = element_line(colour = "dark grey"))
    
    g1 <- ggplot(p, aes(datetime, p)) +
        geom_bar(stat = 'identity', fill = "blue") +
        theme_bw(base_size = 12) +
        ylab("Precip (m)") +
        scale_x_date(date_labels = '%b', date_breaks = '1 month')+
        # labs(title = paste0(gName, "@", sName)) +
        scale_y_reverse()+
        theme(axis.title.x    = element_blank(),
              axis.text.x     = element_blank(),
              axis.ticks.x    = element_blank())+
        theme(panel.grid.major.x = element_line(colour = "dark grey"))
    
    resPlot <- ggplot(p, aes(datetime, rel_res))+
        geom_bar(stat = 'identity',aes(group = 1, fill=relres0))+
        scale_fill_manual(values=c('blue','red'))+
        scale_x_date(date_labels = '%b', date_breaks = '1 month')+
        ylab("rel res (%)") +
        theme_bw(base_size = 12)+
        theme(legend.position = "none",
              axis.title.x    = element_blank(),
              axis.text.x     = element_blank(),
              axis.ticks.x    = element_blank())+
        theme(panel.grid.major.x = element_line(colour = "dark grey"))
    
    g2 <- ggplot(p, aes(datetime, value, color = model))+
        geom_line() +
        ylab("Q (cms)") +
        scale_color_manual(values = c("black", "red", 'green', 'blue')) +
        theme_bw(base_size = 12) +
        geom_hline(yintercept = 0, lty=2, col='dark grey')+
        scale_x_date(date_labels = '%b', date_breaks = '1 month')+
        theme(legend.background = element_rect(fill='transparent',color='transparent'),
              legend.justification=c(1,0), legend.position=c(0.2,0.65),
              # legend.margin = margin(r=0.2, unit="cm"),
              legend.key = element_rect(colour = 'transparent', fill = 'transparent'),
              legend.title=element_blank())+
        theme(panel.grid.major.x = element_line(colour = "dark grey"))
    
    grid.arrange(
        arrangeGrob(cowplot::plot_grid(g0, g1, resPlot, g2, 
                                       align = "v", ncol=1, 
                                       rel_heights = c(1,1,1,3)),
                    ncol = 1
        ), top=as.character(i))
}

#hydrograph
ts_q2 <- rf.result %>% 
    mutate(temp0=ifelse(t>0, 'T>0', 'T<=0') %>% as.factor) %>%
    mutate(rel_res=res/obs*100) %>% 
    mutate(relres0=ifelse(rel_res>0, 'T>0', 'T<=0') %>% as.factor)

for(i in 1981:1990){
    plotHydrograph(i)
}



```

## Test period

```{r}
for(i in 1991:2000){
    plotHydrograph(i)
}

```

