---
title: "Discussion_extra"
author: "Youchen"
date: "5/6/2020"
output: slidy_presentation
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source('function_0_loadLibrary.R')
```

## Using the predictions that are calibrated for the Basel station

```{r}
# input:
calibrMod <- 'calibrated'      # calibrated    uncalibrated
# station_i <- 1                         # station id
trainPeriod <- 1981:1990
testPeriod <- 1991:2000
# plotTitle <- stationInfo$plotName[station_i]
repeatedCV <- F # whether repeated two-fold cv


stationInfo <- read.csv('../data/rawData/stationLatLon.csv')
station <- stationInfo$station
station <- factor(station, levels = c('Basel','Maxau','Lobith','Cochem','Wuerzburg'))

if(repeatedCV){
    rf.eval <- read.csv(paste0('../data/result_', calibrMod,'/repeatedcv/rf_eval.csv'))
}else rf.eval <- read.csv(paste0('../data/result_', calibrMod,'/rf_eval.csv'))
if(repeatedCV){
    vi <- read.csv(paste0('../data/result_', calibrMod,'/repeatedcv/variable_importance.csv'))
}else vi <- read.csv(paste0('../data/result_', calibrMod,'/variable_importance.csv'))

rf.eval <- rf.eval %>%
    mutate(station=factor(station, 
                          levels = c('Basel','Maxau','Lobith','Cochem','Wuerzburg'))) %>% 
    mutate(plotTitle=factor(plotTitle,
                            levels = c('Basel (Rhine)','Maxau (Rhine)', 'Lobith (Rhine)',
                                       'Cochem (Moselle)', 'Wuerzburg (Main)')))

rf.eval_gather <- gather(rf.eval, key='key', value='value', 
                         c('KGE','KGE_corrected','RMSE','RMSE_corrected')) %>%
    mutate(gof=ifelse(grepl('RMSE', key), 'RMSE', 'KGE')) %>% 
    mutate(model=ifelse(grepl('corrected', key), 'RF-corrected', 'pcr-globwb'))

ggplot(data = rf.eval_gather, aes(x=station, y=value, fill=model))+
    geom_col(position = 'dodge')+
    facet_grid(gof~datatype, scale='free')+
    theme_gray(base_size = 16)+
    labs(title = 'Model performance at different stations', y='GOF value')+
    scale_fill_manual(values=c("#00BFC4", "#F8766D"))
    # geom_text(aes(x=station, y=value,
    #               label=round(value, digits=2)),
    #           position=position_dodge(width = 1),
    #           size=4.5)

ggplot(data = rf.eval_gather, aes(x=station, y=value, fill=model))+
    geom_col(position = 'dodge')+
    facet_grid(gof~datatype, scale='free')+
    theme_gray(base_size = 16)+
    labs(title = 'Model performance at different stations', y='GOF value')+
    scale_fill_manual(values=c("#00BFC4", "#F8766D"))+
    geom_text(aes(x=station, y=value,
                  label=round(value, digits=2)),
              position=position_dodge(width = 1),
              size=4.5)
```

## Variable importance

```{r, fig.width=15, fig.height=4, echo=F}
vi_gather <- vi %>% gather('station', 'importance', -names) %>% 
    mutate(station=factor(station, levels = c('Basel','Maxau','Lobith','Cochem','Wuerzburg')))%>% 
    group_by(station) %>% 
    mutate(rank=importance %>% desc %>% rank %>% as.numeric()) %>% 
    mutate(rank=ifelse(rank>5,'',rank))

pList <- list()
stationOrder <- c(1,4,3,2,5)
for(id in 1:length(station)){
    station_i <- stationOrder[id]
    source('function_1_readData.R')
    plotTitle <- stationInfo$plotName[station_i]
    # print(plotTitle)
    imp <- vi[as.character(station[station_i])]
    imp_df <- data.frame(pred=vi$names, importance=imp) %>% 
        mutate(pred=as.character(pred))
    names(imp_df)[2] <- 'importance'
    corData1 <-  all %>% 
        group_by(datatype) %>% 
        mutate(res=(res-mean(res))/sd(res)) %>% as.data.frame() %>% 
        gather(., key='pred','value', c(all_of(feature),-'day'))
        # mutate(predtype=case_when(pred%in%snownames ~ 'snow', 
        #                           pred%in%stornames ~ 'storage',
        #                           pred%in%waternames ~ 'water',
        #                           pred%in%wdlnames ~ 'withdrawal',
        #                           pred%in%etnames ~ 'ET',
        #                           pred%in%c('t','p') ~ 'meteor'))
    
    corDatac <- corData1 %>% 
        group_by(pred) %>%      #datatype
        summarise(cor=cor(value, res), 
               corSign=ifelse(cor>0, '+', '-')) %>% 
        as.data.frame() %>% 
        inner_join(., imp_df, by='pred') %>% 
        mutate(importance=sqrt(importance))
    
    pList[[id]] <- ggplot(corDatac %>% 
               gather('key','value', c('cor','importance'))
           ) +
        geom_col(aes(reorder(pred, value), value),
                 position = 'dodge', fill='khaki') +
        # geom_col(aes(reorder(pred, importance), cor))+
        coord_flip() +
        facet_grid(.~key, scale='free')+
        labs(x='names', y='mean decrease in node impurity (sd)')+
        ggtitle(plotTitle)
        # scale_fill_discrete(name = "Station", 
        #                     labels = station[station_i])+
        # geom_text(aes(x=reorder(pred, value), y=value, 
        #               label=round(value,2)),
        #           size=3, position = position_dodge(0.1))
    
}

grid.arrange(pList[[1]], pList[[2]], pList[[3]], nrow=1)
```

## Variable importance

```{r, fig.width=10, fig.height=4}
grid.arrange(pList[[4]], pList[[5]], nrow=1)

```



